### ISSUE TITLE
ItemSearch throws error PostgresSyntaxError","description":"syntax error at or near \") when fetching items

### ISSUE THREAD

**Issue by jometho** [stac-utils/pystac-client#395] opened 2023-01-03 13:02 UTC
When I do a stac search against the Planetary Computer stac api (https://planetarycomputer.microsoft.com/api/stac/v1) and get the ItemSearch, then trying to get the individual items from the paginated ItemSearch, oine of the pages throws an exception with the following error
`"code":"PostgresSyntaxError","description":"syntax error at or near \")\""`

Wraping the loop like so does not catrch the exception that seems to come from stac_utils.
`    try:
        for item in items:
            results.append(compose_results(item, geojson_aoi))
    except:`

Consequently, we loose all the items in this Item Search, is an improvement that could be done to gracefully handle these errors. I suspect the problem is while getting the paginated items one of the queries parses a bad character to Postgres on Planetary server side and hence the error. But I'm out of options on how to handle it and continue with the remaining good results.

**Comment by TomAugspurger** [comment] 2023-01-03 14:05
Thanks for the report. Can you share a reproducible example? (http://blog.dask.org/2018/02/28/minimal-bug-reports has some tips on building these)

**Comment by mmcfarland** [comment] 2023-01-03 20:00
Thanks for the report @jometho, I'm tracking this as a new pgstac bug, https://github.com/stac-utils/pgstac/issues/152. 

The root cause of the issue is triggered when a page-token is used and there are multiple sorts with differing directions. As a temporary workaround for this particular query, you could increase the `limit` to avoid a second page (there are 104 results, and the page size is 100), or you could drop one of the sorts. We'll get the fix deployed to the Planetary Computer API once it's resolved in the upstream project.

**Comment by gadomski** [comment] 2023-05-09 18:46
Using @jometho's excellent example, I confirmed that this is now fixed. Thanks for the report!

**Closed by gadomski** 2023-05-09 18:46 UTC
Labels: bug, planetary-computer
