### ISSUE TITLE
0.3.3 does not support/has trouble with stac api version < 1.0.0

### ISSUE THREAD

**Issue by Scartography** [stac-utils/pystac-client#159] opened 2022-05-13 10:25 UTC
Have got latest version of the `pystac-client==0.3.3` but having trouble to read from older stac API versions

The issue is when trying to use the `pystac-client==0.3.3`. with https://earth-search.aws.element84.com/v0/ endpoint

Or has the `search` syntax changed from the 0.3.2 versions?

Thanks for any help/comment.

Peter

**Comment by julianblue** [comment] 2022-05-14 12:03
I believe this is linked to #141 .

**Comment by aazuspan** [comment] 2022-05-15 21:36
This is caused by `pystac-client==0.3.3` [strictly requiring](https://github.com/stac-utils/pystac-client/blob/c23012022070cd3c33ab4047876690d91cf83586/pystac_client/client.py#L171) GeoJSON search endpoints, as specified by [STAC API 1.0.0](https://github.com/radiantearth/stac-api-spec/tree/master/item-search#link-relations). Trying to search APIs still using JSON (like [Element84](https://earth-search.aws.element84.com/v0/)) now raises `No link with "rel" type of "search" could be found in this catalog`.

Obviously the ideal solution would be for those APIs to adopt the `1.0.0` spec, but in the meantime could a backwards compatibility option be added to override the strict type requirement? Or alternatively, remove the type requirement altogether and raise a deprecation warning for a future `pystac-client` release? As is, it's a pretty serious breaking change with no workaround other than downgrading to `0.3.2`.

**Comment by samsipe** [comment] 2022-05-17 19:55
Any updates on this from the development team? This is going to cause a lot of headaches for people using Earth Search and other no `1.0.0` APIs.

**Comment by gadomski** [comment] 2022-05-17 20:01
As mentioned above, you can use `pystac-client != 0.3.3` as a workaround. Once #160 is merged, we plan to release a v0.3.4 that should fix the issue.

**Closed** 2022-05-18 14:59 UTC

**Comment by gadomski** [comment] 2022-05-25 14:38
v0.3.4 is out w/ the fix: https://github.com/stac-utils/pystac-client/releases/tag/v0.3.4.
