### ISSUE TITLE
STACTypeError when reading catalogs for stac_version:1.0.0

### ISSUE THREAD

**Issue by romulogoncalves** [stac-utils/pystac-client#162] opened 2022-05-19 13:15 UTC
We are waiting for the release of `pystac-client:0.3.4` to be able to read `https://earth-search.aws.element84.com/v0` (it it uses stac_version:1.0.0-beta.2), however we would like to point out that version `0.3.3` is also not able to read catalogs `stac_version: 1.0.0`.

Using version `0.3.3` and the catalog from `https://earth-search.aws.element84.com/v1`:
```Python
catalog = Client.open(url='https://earth-search.aws.element84.com/v1')
for collection in catalog.get_all_collections():
    print(collection)
```

We are getting the following error:
```
STACTypeError: {'id': 'sentinel-2-l1c', 'stac_version': '1.0.0', 'description': 'Sentinel-2a and Sentinel-2b imagery, processed to Level 1C (Top-Of-Atmosphere Geometrically Corrected)', 'links': [{'rel': 'self', 'href': 'https://earth-search.aws.element84.com/v1/collections/sentinel-2-l1c'}, {'rel': 'license', 'href': 'https://sentinel.esa.int/documents/247904/690755/Sentinel_Data_Legal_Notice'}, {'rel': 'about', 'href': 'https://registry.opendata.aws/sentinel-2'}, {'rel': 'parent', 'href': 'https://earth-search.aws.element84.com/v1/'}, {'rel': 'root', 'href': 'https://earth-search.aws.element84.com/v1/'}, {'rel': 'items', 'href': 'https://earth-search.aws.element84.com/v1/collections/sentinel-2-l1c/items'}], 'stac_extensions': ['item-assets'], 'title': 'Sentinel-2 L1C', 'keywords': ['sentinel', 'earth observation', 'esa'], 'providers': [{'name': 'ESA', 'roles': ['producer'], 'url': 'https://earth.esa.int/web/guest/home'}, {'name': 'Sinergise', 'roles': ['processor'], 'url': 'https://registry.opendata.aws/sentinel-2/'}, {'name': 'AWS', 'roles': ['host'], 'url': 'http://sentinel-pds.s3-website.eu-central-1.amazonaws.com/'}, {'name': 'Element 84', 'roles': ['processor'], 'url': 'https://element84.com/'}], 'summaries': {'platform': ['sentinel-2a', 'sentinel-2b'], 'constellation': ['sentinel-2'], 'instruments': ['msi'], 'gsd': [10], 'view:off_nadir': [0]}, 'item_assets': {'thumbnail': {'title': 'Thumbnail', 'type': 'image/png', 'roles': ['thumbnail']}, 'overview': {'title': 'True color image', 'type': 'image/jp2', 'roles': ['overview'], 'gsd': 10, 'eo:bands': [{'name': 'B04', 'common_name': 'red', 'center_wavelength': 0.6645, 'full_width_half_max': 0.038}, {'name': 'B03', 'common_name': 'green', 'center_wavelength': 0.56, 'full_width_half_max': 0.045}, {'name': 'B02', 'common_name': 'blue', 'center_wavelength': 0.4966, 'full_width_half_max': 0.098}]}, 'info': {'title': 'Original JSON metadata', 'type': 'application/json', 'roles': ['metadata']}, 'metadata': {'title': 'Original XML metadata', 'type': 'application/xml', 'roles': ['metadata']}, 'B01': {'title': 'Band 1 (coastal)', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 60, 'eo:bands': [{'name': 'B01', 'common_name': 'coastal', 'center_wavelength': 0.4439, 'full_width_half_max': 0.027}]}, 'B02': {'title': 'Band 2 (blue)', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 10, 'eo:bands': [{'name': 'B02', 'common_name': 'blue', 'center_wavelength': 0.4966, 'full_width_half_max': 0.098}]}, 'B03': {'title': 'Band 3 (green)', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 10, 'eo:bands': [{'name': 'B03', 'common_name': 'green', 'center_wavelength': 0.56, 'full_width_half_max': 0.045}]}, 'B04': {'title': 'Band 4 (red)', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 10, 'eo:bands': [{'name': 'B04', 'common_name': 'red', 'center_wavelength': 0.6645, 'full_width_half_max': 0.038}]}, 'B05': {'title': 'Band 5', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 20, 'eo:bands': [{'name': 'B05', 'center_wavelength': 0.7039, 'full_width_half_max': 0.019}]}, 'B06': {'title': 'Band 6', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 20, 'eo:bands': [{'name': 'B06', 'center_wavelength': 0.7402, 'full_width_half_max': 0.018}]}, 'B07': {'title': 'Band 7', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 20, 'eo:bands': [{'name': 'B07', 'center_wavelength': 0.7825, 'full_width_half_max': 0.028}]}, 'B08': {'title': 'Band 8 (nir)', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 10, 'eo:bands': [{'name': 'B08', 'common_name': 'nir', 'center_wavelength': 0.8351, 'full_width_half_max': 0.145}]}, 'B8A': {'title': 'Band 8A', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 20, 'eo:bands': [{'name': 'B8A', 'center_wavelength': 0.8648, 'full_width_half_max': 0.033}]}, 'B09': {'title': 'Band 9', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 60, 'eo:bands': [{'name': 'B09', 'center_wavelength': 0.945, 'full_width_half_max': 0.026}]}, 'B10': {'title': 'Band 10 (cirrus)', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 60, 'eo:bands': [{'name': 'B10', 'common_name': 'cirrus', 'center_wavelength': 1.3735, 'full_width_half_max': 0.075}]}, 'B11': {'title': 'Band 11 (swir16)', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 20, 'eo:bands': [{'name': 'B11', 'common_name': 'swir16', 'center_wavelength': 1.6137, 'full_width_half_max': 0.143}]}, 'B12': {'title': 'Band 12 (swir22)', 'type': 'image/jp2', 'roles': ['data'], 'gsd': 20, 'eo:bands': [{'name': 'B12', 'common_name': 'swir22', 'center_wavelength': 2.22024, 'full_width_half_max': 0.242}]}}, 'extent': {'spatial': {'bbox': [[-180, -90, 180, 90]]}, 'temporal': {'interval': [['2015-06-27T10:25:31.456000Z', None]]}}, 'license': 'proprietary'} does not represent a CollectionClient instance
```

If you need more information, please let us know.

**Comment by philvarner** [comment] 2022-05-19 15:09
That is a problem with the collection. IIRC, stac-server just returns whatever is in ES as the collection, so this (superficially) a problem with the collection document that's stored in ES, then at another level the API should fix the document to ensure it's a valid collection before returning it, then at another level there should be ingest validation to ensure that the collections and items that are ingested are valid STAC objects.

So, the immediate fix to to update the collection document in the ES db to include type collection.  

This Elastic query might do it
```
curl -X "POST" "http://<es_url>/collections/_update_by_query?wait_for_completion=true&conflicts=abort" \
     -H 'Content-Type: application/json; charset=utf-8' \
     -d $'{
  "query": {
    "match_all": {}
  },
  "script": {
    "lang": "painless",
    "params": {
      "type": "Collection"
    },
    "source": "ctx._source.type = params.type"
  }
}'
```

**Comment by matthewhanson** [comment] 2022-05-19 16:25
@romulogoncalves, the v1 endpoint has not been finalized (it only contains data from the last several days) and we will be clearing it out soon and kicking it off again (along with ingesting historical data).  Thanks for the report though, @gadomski is correct that this is due to the missing type field and we'll update it.

**Comment by gadomski** [comment] 2022-05-19 16:29
Closing as invalid because the issue is w/ another project. @matthewhanson is there an issue tracker that we can link to for this fix?

**Closed by gadomski** 2022-05-19 16:29 UTC
Labels: invalid
